Titulos conceptos
geraldvindas/TCU_655_Mi_cuenca pull request #19
Opened 2019-09-05 05:12 UTC by felipeSolisJimenez

Listo los cambios

2019-09-06 06:49 UTC, felipeSolisJimenez commented
@geraldvindas Hice la parte de ASADAs en este branch también

2019-09-07 21:26 UTC, geraldvindas requested changes
Quitar esta línea 
>android:background="@drawable/rounded_corners"

Ya que esto solo se usa en el RecyclerView

2019-09-07 21:26 UTC, geraldvindas commented on app/src/main/res/layout/info_asadas.xml
> +        android:background="@drawable/rounded_corners"
Quitar eso.

2019-09-07 21:26 UTC, geraldvindas commented on app/src/main/res/layout/info_asadas.xml
> +        android:background="@drawable/rounded_corners"
Esto quitarlo.

2019-09-07 21:26 UTC, geraldvindas commented on app/src/main/res/layout/info_asadas.xml
> +    android:background="@drawable/rounded_corners"
Esto quitarlo.

2019-09-07 21:26 UTC, geraldvindas commented on app/src/main/res/layout/info_asadas.xml
> +        android:background="@drawable/rounded_corners"
Esto quitarlo.

2019-09-07 21:26 UTC, geraldvindas commented on app/src/main/res/layout/info_asadas.xml
> +        android:background="@drawable/rounded_corners"
Esto quitarlo.

2019-09-07 21:26 UTC, geraldvindas commented on app/src/main/res/layout/info_asadas.xml
> +        android:background="@drawable/rounded_corners"
Esto quitarlo.

2019-09-07 21:26 UTC, geraldvindas commented on app/src/main/res/layout/info_asadas.xml
> +        android:background="@drawable/rounded_corners"
Esto quitarlo.

2019-09-08 21:57 UTC, geraldvindas approved these changes
Gracias, por las actualizaciones!

2019-09-08 21:57 UTC, merged